# Generated by Django 2.2.7 on 2019-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='created_date',
        ),
        migrations.AddField(
            model_name='livros',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
